import { useCallback, useState } from "react";
import { type LedgerRow, type OpenBalanceRow, type StatementRow, type TrialBalanceRow } from "../../../platform/tauri/phase08";
import { Button, StateBlock, TODAY, Table, previewTrial, useResource, type Copy, type Gateway } from "../shared";

export function Statements({ gateway, c, formatMoney }: { gateway: Gateway; c: Copy; formatMoney: (n: number) => string }) {
  const [partner, setPartner] = useState("customer-1");
  const statement = useResource(useCallback(signal => gateway ? gateway.call<StatementRow[]>("get_partner_statement", partner, signal) : Promise.resolve([{ eventDate: TODAY, sourceType: "SALES_INVOICE", sourceId: "invoice-7", debitMinor: 119000, creditMinor: 0, runningBalanceMinor: 119000 }]), [gateway, partner]), []);
  const receivables = useResource(useCallback(signal => gateway ? gateway.call<OpenBalanceRow[]>("get_open_receivables", undefined, signal) : Promise.resolve([{ documentId: "invoice-7", documentNumber: "FAC000007", documentType: "SALES_INVOICE", commercialDate: TODAY, totalMinor: 119000, allocatedMinor: 40000, openMinor: 79000 }]), [gateway]), []);
  const payables = useResource(useCallback(signal => gateway ? gateway.call<OpenBalanceRow[]>("get_open_payables", undefined, signal) : Promise.resolve([{ documentId: "purchase-4", documentNumber: "FA000004", documentType: "PURCHASE_INVOICE", commercialDate: TODAY, totalMinor: 238000, allocatedMinor: 60000, openMinor: 178000 }]), [gateway]), []);
  const balances = (rows: OpenBalanceRow[]) => rows.map(row => [row.documentNumber, formatMoney(row.totalMinor), formatMoney(row.allocatedMinor), formatMoney(row.openMinor)]);
  return <div className="p8-stack"><section className="p8-paper p8-filter"><label>{c.partner}<input value={partner} onChange={event => setPartner(event.target.value)} /></label><Button type="button" onClick={statement.reload}>{c.retry}</Button></section><StateBlock state={statement.state} retry={statement.reload} c={c}><Table headers={[c.date, c.reference, c.debit, c.credit, c.openBalance]} rows={statement.value.map(row => [row.eventDate, `${row.sourceType} · ${row.sourceId}`, formatMoney(row.debitMinor), formatMoney(row.creditMinor), formatMoney(row.runningBalanceMinor)])} /></StateBlock><section className="p8-paper"><h3>{c.receivables}</h3><StateBlock state={receivables.state} retry={receivables.reload} c={c}><Table headers={[c.document, c.amount, c.allocate, c.openBalance]} rows={balances(receivables.value)} /></StateBlock></section><section className="p8-paper"><h3>{c.payables}</h3><StateBlock state={payables.state} retry={payables.reload} c={c}><Table headers={[c.document, c.amount, c.allocate, c.openBalance]} rows={balances(payables.value)} /></StateBlock></section></div>;
}

export function Ledger({ gateway, c, formatMoney }: { gateway: Gateway; c: Copy; formatMoney: (n: number) => string }) {
  const [accountId, setAccountId] = useState("acc-411");
  const trial = useResource(useCallback(signal => gateway ? gateway.call<TrialBalanceRow[]>("get_trial_balance", undefined, signal) : Promise.resolve(previewTrial), [gateway]), previewTrial);
  const ledger = useResource(useCallback(signal => gateway ? gateway.call<LedgerRow[]>("get_general_ledger", undefined, signal) : Promise.resolve([{ journalEntryId: "je-sale-7", entryNumber: "20260806-000007", entryDate: TODAY, accountId: "acc-411", accountCode: "411", description: "FAC000007", debitMinor: 119000, creditMinor: 0, runningBalanceMinor: 119000 }]), [gateway]), []);
  const accountLedger = useResource(useCallback(signal => gateway ? gateway.call<LedgerRow[]>("get_account_ledger", accountId, signal) : Promise.resolve([]), [gateway, accountId]), []);
  const cash = useResource(useCallback(signal => gateway ? gateway.call<LedgerRow[]>("get_cash_bank_register", undefined, signal) : Promise.resolve([]), [gateway]), []);
  const rows = (items: LedgerRow[]) => items.map(row => [row.entryDate, row.entryNumber, `${row.accountCode} · ${row.description}`, formatMoney(row.debitMinor), formatMoney(row.creditMinor), formatMoney(row.runningBalanceMinor)]);
  const headers = [c.date, c.reference, c.account, c.debit, c.credit, c.openBalance];
  return <div className="p8-stack"><StateBlock state={trial.state} retry={trial.reload} c={c}><Table headers={[c.account, c.debit, c.credit, c.openBalance]} rows={trial.value.map(row => [`${row.accountCode} · ${row.accountNameAr}`, formatMoney(row.debitMinor), formatMoney(row.creditMinor), formatMoney(row.balanceMinor)])} /></StateBlock><StateBlock state={ledger.state} retry={ledger.reload} c={c}><Table headers={headers} rows={rows(ledger.value)} /></StateBlock><section className="p8-paper"><h3>{c.accountLedger}</h3><div className="p8-filter"><label>{c.account}<input value={accountId} onChange={event => setAccountId(event.target.value)} /></label><Button type="button" onClick={accountLedger.reload}>{c.retry}</Button></div><StateBlock state={accountLedger.state} retry={accountLedger.reload} c={c}><Table headers={headers} rows={rows(accountLedger.value)} /></StateBlock></section><section className="p8-paper"><h3>{c.cashRegister}</h3><StateBlock state={cash.state} retry={cash.reload} c={c}><Table headers={headers} rows={rows(cash.value)} /></StateBlock></section></div>;
}
