import type { Phase09Locale } from "../../platform/tauri/phase09";

export const phase09Copy = {
  "ar-DZ": {
    title: "الوثائق والتقارير والحماية المحلية",
    subtitle: "إخراج A4، تقارير تشغيلية، سجل التدقيق، والنسخ الاحتياطي المحلي.",
    documents: "الوثائق",
    templates: "القوالب",
    reports: "التقارير",
    audit: "سجل التدقيق",
    backup: "النسخ والاستعادة",
    loading: "جارٍ تنفيذ العملية المحلية…",
    empty: "لا توجد بيانات مطابقة.",
    denied: "ليست لديك الصلاحية المطلوبة لهذه المساحة.",
    retry: "إعادة المحاولة",
    preview: "معاينة",
    render: "إنشاء PDF تاريخي",
    verify: "التحقق من السلامة",
    export: "تصدير",
    print: "طباعة",
    createDraft: "إنشاء مسودة",
    saveDraft: "حفظ المسودة",
    publish: "نشر النسخة",
    retire: "سحب النسخة",
    runReport: "تشغيل التقرير",
    exportCsv: "تصدير CSV",
    exportPdf: "تصدير PDF",
    applyFilters: "تطبيق المرشحات",
    createBackup: "إنشاء نسخة يدوية",
    importBackup: "استيراد نسخة",
    restore: "استعادة البيانات",
    deleteBackup: "حذف النسخة",
    unencrypted: "النسخ الاحتياطية محلية وغير مشفرة.",
    integrityOk: "تم التحقق من سلامة الأثر.",
    integrityWarning: "تعذر التحقق من الأثر التاريخي. لم يتم استبداله.",
    restoreWarning: "الاستعادة عملية مدمرة تتطلب كلمة المرور وكتابة RESTORE.",
    confirmation: "تأكيد صريح",
    password: "كلمة المرور الحالية",
    confirmationText: "اكتب RESTORE",
    documentType: "نوع الوثيقة",
    sourceId: "معرّف المصدر",
    locale: "اللغة",
    state: "الحالة",
    hash: "البصمة SHA-256",
    filters: "المرشحات",
    startDate: "من",
    endDate: "إلى",
    outcome: "النتيجة",
    sensitiveOnly: "الأحداث الحساسة فقط",
    enabled: "مفعّل",
    weekly: "نسخة أسبوعية",
    automatic: "نسخ تلقائي",
    close: "إغلاق",
  },
  "fr-DZ": {
    title: "Documents, rapports et protection locale",
    subtitle: "Sorties A4, rapports opérationnels, audit et sauvegarde locale.",
    documents: "Documents",
    templates: "Modèles",
    reports: "Rapports",
    audit: "Audit",
    backup: "Sauvegarde et restauration",
    loading: "Opération locale en cours…",
    empty: "Aucune donnée correspondante.",
    denied: "Vous ne disposez pas de l’autorisation requise.",
    retry: "Réessayer",
    preview: "Aperçu",
    render: "Créer le PDF historique",
    verify: "Vérifier l’intégrité",
    export: "Exporter",
    print: "Imprimer",
    createDraft: "Créer un brouillon",
    saveDraft: "Enregistrer le brouillon",
    publish: "Publier la version",
    retire: "Retirer la version",
    runReport: "Exécuter le rapport",
    exportCsv: "Exporter CSV",
    exportPdf: "Exporter PDF",
    applyFilters: "Appliquer les filtres",
    createBackup: "Créer une sauvegarde manuelle",
    importBackup: "Importer une sauvegarde",
    restore: "Restaurer les données",
    deleteBackup: "Supprimer la sauvegarde",
    unencrypted: "Les sauvegardes sont locales et non chiffrées.",
    integrityOk: "L’intégrité de l’artefact est vérifiée.",
    integrityWarning: "L’artefact historique n’a pas pu être vérifié. Il n’a pas été remplacé.",
    restoreWarning: "La restauration est destructive et exige le mot de passe et le texte RESTORE.",
    confirmation: "Confirmation explicite",
    password: "Mot de passe actuel",
    confirmationText: "Saisissez RESTORE",
    documentType: "Type de document",
    sourceId: "Identifiant source",
    locale: "Langue",
    state: "État",
    hash: "Empreinte SHA-256",
    filters: "Filtres",
    startDate: "Du",
    endDate: "Au",
    outcome: "Résultat",
    sensitiveOnly: "Événements sensibles uniquement",
    enabled: "Activé",
    weekly: "Sauvegarde hebdomadaire",
    automatic: "Sauvegarde automatique",
    close: "Fermer",
  },
} as const;

export type Phase09Copy = (typeof phase09Copy)[Phase09Locale];
