import assert from "node:assert/strict";
import test from "node:test";

import { PHASE07_COMMANDS,Phase07GatewayError,createPhase07Gateway,normalizePhase07Error,validateAvailability,validateFlow,validateSummary } from "../../src/platform/tauri/phase07.ts";

const entity={id:"invoice-1",documentNumber:"FAC000001",status:"POSTED",rowVersion:2,replayed:false};
const summary={draftOrders:1,confirmedOrders:2,partialOrders:1,uninvoicedDeliveries:3,postedInvoices:4,belowCostOverrides:1};

test("PHASE 07 gateway invokes exact local commands with one request envelope",async()=>{const calls:Array<{command:string;args?:Record<string,unknown>}>=[];const gateway=createPhase07Gateway(async(command,args)=>{calls.push({command,args});if(command==="get_sales_summary")return summary;return entity});const request={idempotencyKey:"sales-confirm-0001",payload:{documentId:"order-1",rowVersion:1}};assert.deepEqual(await gateway.call("confirm_sales_order",request),entity);assert.deepEqual(calls[0],{command:"confirm_sales_order",args:{request}});assert.deepEqual(await gateway.summary(),summary);assert.deepEqual(calls[1],{command:"get_sales_summary",args:undefined})});
test("all fourteen PHASE 07 commands are typed and present",()=>{assert.equal(PHASE07_COMMANDS.length,14);for(const command of ["create_sales_order","deliver_sales_order","invoice_sales_delivery","direct_sale","post_sales_return","get_sales_line_availability"])assert.ok(PHASE07_COMMANDS.includes(command as never),command)});
test("sales response validators reject malformed numeric and object data",()=>{assert.deepEqual(validateSummary(summary),summary);assert.deepEqual(validateFlow({primary:entity,relatedDocumentIds:["delivery-1"]}),{primary:entity,relatedDocumentIds:["delivery-1"]});assert.deepEqual(validateAvailability([{sourceLineId:"line-1",productId:"product-1",originalQuantityScaled:20_000_000,deliveredQuantityScaled:8_000_000,invoicedQuantityScaled:8_000_000,returnedQuantityScaled:0,remainingQuantityScaled:12_000_000}])[0].remainingQuantityScaled,12_000_000);assert.throws(()=>validateSummary({...summary,postedInvoices:1.5}),Phase07GatewayError);assert.throws(()=>validateFlow({primary:null,relatedDocumentIds:[]}),Phase07GatewayError)});
test("known sales errors remain safe and unknown details are discarded",async()=>{assert.equal(normalizePhase07Error({code:"BELOW_COST_OVERRIDE_REQUIRED",message:"SELECT password_hash /private/db"}).code,"BELOW_COST_OVERRIDE_REQUIRED");assert.equal(normalizePhase07Error(new Error("sqlite SELECT /customer/db")).code,"OPERATION_FAILED");const gateway=createPhase07Gateway(async()=>{throw{code:"INSUFFICIENT_STOCK",message:"SELECT * FROM stock_movements"}});await assert.rejects(gateway.call("direct_sale",{}),(error:unknown)=>error instanceof Phase07GatewayError&&error.code==="INSUFFICIENT_STOCK"&&!error.message.includes("SELECT"))});
test("production gateway keeps injection behind DEV and contains no network client",async()=>{const{readFile}=await import("node:fs/promises");const source=await readFile("src/platform/tauri/phase07.ts","utf8");assert.match(source,/import\.meta\.env\.DEV/);assert.match(source,/isTauri\(\)/);assert.match(source,/@tauri-apps\/api\/core/);for(const token of ["fetch(","XMLHttpRequest","WebSocket(","axios."])assert.equal(source.includes(token),false,token)});
