export const PHASE08_SECTIONS = [
  "overview",
  "accounts",
  "rules",
  "journals",
  "payments",
  "statements",
  "ledger",
  "periods",
  "queue",
] as const;

export type Phase08Section = (typeof PHASE08_SECTIONS)[number];

export const PHASE08_COPY = {
  "ar-DZ": {
    title: "دفتر العمليات المحاسبي",
    subtitle: "تهيئة محاسبية، ترحيل آلي، دفعات وتخصيصات ضمن قاعدة POSMAN المحلية",
    ready: "متصل بقاعدة SQLite المحلية",
    preview: "معاينة تشغيلية دون اتصال بالخدمة",
    overview: "حالة المحاسبة",
    accounts: "الحسابات والأدوار",
    rules: "قواعد الترحيل",
    journals: "القيود اليومية",
    payments: "التحصيلات والمدفوعات",
    statements: "كشوف الشركاء",
    ledger: "ميزان المراجعة والأستاذ",
    periods: "الفترات المالية",
    queue: "محاولات الترحيل",
    loading: "جارٍ تحميل البيانات المحلية…",
    empty: "لا توجد بيانات في هذا النطاق.",
    error: "تعذر تحميل البيانات. صحّح الإعداد ثم أعد المحاولة.",
    retry: "إعادة المحاولة",
    save: "حفظ",
    create: "إنشاء",
    post: "ترحيل",
    reverse: "عكس",
    allocate: "تخصيص",
    close: "إغلاق الفترة",
    reopen: "إعادة فتح الفترة",
    confirmPost: "سيُنشأ سجل محاسبي غير قابل للتعديل. هل تريد المتابعة؟",
    confirmReverse: "سيُنشأ سجل تعويضي جديد دون تعديل التاريخ. هل تريد المتابعة؟",
    confirmPeriod: "تغيير حالة الفترة يؤثر في قبول الترحيل. هل تريد المتابعة؟",
    success: "اكتملت العملية محليًا.",
    accountCode: "رمز الحساب",
    arabicName: "الاسم بالعربية",
    frenchName: "الاسم بالفرنسية",
    accountType: "نوع الحساب",
    normalSide: "الطبيعة",
    journalCode: "رمز اليومية",
    eventType: "حدث المصدر",
    amount: "المبلغ",
    customer: "العميل",
    supplier: "المورد",
    paymentMethod: "طريقة الدفع",
    document: "المستند",
    date: "التاريخ",
    reason: "السبب",
    status: "الحالة",
    debit: "مدين",
    credit: "دائن",
    unallocated: "غير مخصص",
    openBalance: "الرصيد المفتوح",
    account: "الحساب",
    partner: "الشريك",
    reference: "المرجع",
    setupIssues: "مشكلات قابلة للإصلاح",
    noIssues: "التهيئة صالحة للترحيل.",
    configureTemplate: "تفعيل التهيئة وربط الأدوار",
    sourceTrace: "تتبع المصدر إلى القيد",
    draftManual: "مسودة قيد يدوي",
    customerReceipt: "تحصيل عميل",
    supplierPayment: "دفع مورد",
    partialAllocation: "تخصيص جزئي أو كامل",
    periodHistory: "حالة الفترات وسجل التغيير",
    failedSafe: "المحاولة الفاشلة محفوظة دون قيد جزئي",
    addLine: "إضافة سطر",
    removeLine: "حذف السطر",
    journalSetup: "إعداد اليوميات",
    paymentMapping: "ربط طرق الدفع",
    reverseAllocation: "عكس التخصيص",
    reversePayment: "عكس الدفع",
    payables: "الذمم الدائنة المفتوحة",
    receivables: "الذمم المدينة المفتوحة",
    accountLedger: "أستاذ الحساب",
    cashRegister: "سجل الصندوق والبنك",
    updateDraft: "تحديث المسودة",
  },
  "fr-DZ": {
    title: "Registre des opérations comptables",
    subtitle: "Paramétrage, comptabilisation automatique, paiements et lettrage dans SQLite local",
    ready: "Connecté à la base SQLite locale",
    preview: "Aperçu opérationnel sans service",
    overview: "État comptable",
    accounts: "Comptes et rôles",
    rules: "Règles de comptabilisation",
    journals: "Écritures comptables",
    payments: "Encaissements et décaissements",
    statements: "Relevés partenaires",
    ledger: "Balance et grand livre",
    periods: "Périodes fiscales",
    queue: "Tentatives de comptabilisation",
    loading: "Chargement des données locales…",
    empty: "Aucune donnée dans ce périmètre.",
    error: "Chargement impossible. Corrigez le paramétrage puis réessayez.",
    retry: "Réessayer",
    save: "Enregistrer",
    create: "Créer",
    post: "Comptabiliser",
    reverse: "Contrepasser",
    allocate: "Lettrer",
    close: "Clôturer la période",
    reopen: "Rouvrir la période",
    confirmPost: "Une écriture immuable sera créée. Continuer ?",
    confirmReverse: "Une écriture compensatrice sera créée sans modifier l’historique. Continuer ?",
    confirmPeriod: "Le changement de période affecte la comptabilisation. Continuer ?",
    success: "Opération locale terminée.",
    accountCode: "Code compte",
    arabicName: "Libellé arabe",
    frenchName: "Libellé français",
    accountType: "Type de compte",
    normalSide: "Sens normal",
    journalCode: "Code journal",
    eventType: "Événement source",
    amount: "Montant",
    customer: "Client",
    supplier: "Fournisseur",
    paymentMethod: "Mode de paiement",
    document: "Document",
    date: "Date",
    reason: "Motif",
    status: "Statut",
    debit: "Débit",
    credit: "Crédit",
    unallocated: "Non lettré",
    openBalance: "Solde ouvert",
    account: "Compte",
    partner: "Partenaire",
    reference: "Référence",
    setupIssues: "Anomalies à corriger",
    noIssues: "Le paramétrage est prêt pour la comptabilisation.",
    configureTemplate: "Activer le paramétrage et associer les rôles",
    sourceTrace: "Traçabilité source vers écriture",
    draftManual: "Brouillon d’écriture manuelle",
    customerReceipt: "Encaissement client",
    supplierPayment: "Paiement fournisseur",
    partialAllocation: "Lettrage partiel ou total",
    periodHistory: "État des périodes et historique",
    failedSafe: "La tentative en échec est conservée sans écriture partielle",
    addLine: "Ajouter une ligne",
    removeLine: "Retirer la ligne",
    journalSetup: "Paramétrage des journaux",
    paymentMapping: "Affectation des modes de paiement",
    reverseAllocation: "Annuler le lettrage",
    reversePayment: "Contrepasser le paiement",
    payables: "Dettes fournisseurs ouvertes",
    receivables: "Créances clients ouvertes",
    accountLedger: "Grand livre du compte",
    cashRegister: "Journal de caisse et banque",
    updateDraft: "Mettre à jour le brouillon",
  },
} as const;
