export type Phase07Locale="ar-DZ"|"fr-DZ";
export type Phase07Screen="today"|"orders"|"orderEditor"|"delivery"|"invoice"|"direct"|"returns"|"lineage"|"policy";
export const PHASE07_SCREENS:readonly Phase07Screen[]=["today","orders","orderEditor","delivery","invoice","direct","returns","lineage","policy"];
export const PHASE07_COPY:Record<Phase07Locale,Record<string,string>>={
 "ar-DZ":{
  title:"المبيعات ودورة العميل",subtitle:"من الحجز إلى التسليم والفوترة — سجل محلي واحد",today:"مكتب مبيعات اليوم",orders:"طلبات العملاء",orderEditor:"طلب عميل جديد",delivery:"التسليم الجزئي والكامل",invoice:"فوترة المسلّم",direct:"بيع مباشر",returns:"المرتجعات والإشعارات الدائنة",lineage:"تتبع المستندات",policy:"سياسة الربح",customer:"العميل",warehouse:"المستودع",product:"المادة أو الباركود",quantity:"الكمية",price:"سعر البيع",discount:"خصم السطر %",headerDiscount:"الخصم العام %",tax:"معرّف الضريبة",date:"التاريخ",dueDate:"تاريخ الاستحقاق",sourceDocument:"المستند المصدر",sourceLine:"سطر المصدر",reason:"السبب الإداري",notes:"ملاحظات",save:"حفظ المسودة",confirm:"تأكيد وحجز",hold:"تعليق وتحرير الحجز",resume:"استئناف الحجز",cancel:"إلغاء",postDelivery:"ترحيل التسليم",postInvoice:"إنشاء الفاتورة",directPost:"ترحيل بيع مباشر",returnPost:"ترحيل المرتجع والإشعار",refresh:"تحديث",retry:"إعادة المحاولة",loading:"جارٍ تحميل سجل المبيعات المحلي…",empty:"لا توجد مستندات مطابقة.",preview:"معاينة محلية ببيانات اصطناعية",ready:"SQLite محلية",success:"تمت العملية محليًا.",error:"تعذر إكمال العملية المحلية.",belowCost:"سعر البيع أقل من CUMP الحالي. المستخدم العادي ممنوع؛ التجاوز الإداري يحتاج سببًا ويُسجل في التدقيق.",pricingOrder:"الكمية × السعر ← خصم السطر ← توزيع الخصم العام ← HT ← الضريبة ← TTC",scan:"مسح سريع",scanHint:"امسح الباركود أو أدخل رمز المادة",document:"المستند",status:"الحالة",total:"الإجمالي TTC",reserved:"الحجز",delivered:"المسلّم",invoiced:"المفوّتَر",returned:"المرتجع",remaining:"المتبقي",postedLocked:"المستند المرحّل مقفل ولا يُعدّل.",confirmPosting:"سيُرحّل هذا الإجراء سجلًا غير قابل للتعديل. هل تريد المتابعة؟",directNote:"البيع المباشر ينشئ سند تسليم داخليًا وفاتورة وحركة مخزون في transaction واحدة.",noAutoExpiry:"لا انتهاء تلقائي للحجز: التعليق أو الإلغاء يحرره صراحةً.",priceMode:"نمط السعر",ht:"HT دون ضريبة",ttc:"TTC شامل الضريبة"
 },
 "fr-DZ":{
  title:"Ventes et cycle client",subtitle:"De la réservation à la livraison et facturation — un registre local",today:"Poste ventes du jour",orders:"Commandes clients",orderEditor:"Nouvelle commande client",delivery:"Livraison partielle ou complète",invoice:"Facturer le livré",direct:"Vente directe",returns:"Retours et avoirs",lineage:"Traçabilité documentaire",policy:"Politique de marge",customer:"Client",warehouse:"Dépôt",product:"Article ou code-barres",quantity:"Quantité",price:"Prix de vente",discount:"Remise ligne %",headerDiscount:"Remise globale %",tax:"Identifiant taxe",date:"Date",dueDate:"Échéance",sourceDocument:"Document source",sourceLine:"Ligne source",reason:"Motif administratif",notes:"Notes",save:"Enregistrer le brouillon",confirm:"Confirmer et réserver",hold:"Suspendre et libérer",resume:"Reprendre la réservation",cancel:"Annuler",postDelivery:"Valider la livraison",postInvoice:"Créer la facture",directPost:"Valider la vente directe",returnPost:"Valider le retour et l’avoir",refresh:"Actualiser",retry:"Réessayer",loading:"Chargement du registre des ventes local…",empty:"Aucun document correspondant.",preview:"Aperçu local avec données synthétiques",ready:"SQLite locale",success:"Opération enregistrée localement.",error:"L’opération locale n’a pas pu être terminée.",belowCost:"Le prix de vente est inférieur au CUMP actuel. L’utilisateur ordinaire est bloqué; la dérogation administrateur exige un motif audité.",pricingOrder:"quantité × prix ← remise ligne ← remise globale ← HT ← taxe ← TTC",scan:"Saisie rapide",scanHint:"Scannez le code-barres ou saisissez le code article",document:"Document",status:"Statut",total:"Total TTC",reserved:"Réservé",delivered:"Livré",invoiced:"Facturé",returned:"Retourné",remaining:"Restant",postedLocked:"Le document validé est verrouillé.",confirmPosting:"Cette action valide un registre immuable. Continuer ?",directNote:"La vente directe crée un bon interne, la facture et le mouvement de stock dans une seule transaction.",noAutoExpiry:"Aucune expiration automatique: suspension ou annulation libère explicitement la réservation.",priceMode:"Mode de prix",ht:"HT hors taxe",ttc:"TTC taxe comprise"
 }
};
